//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.DOSI_POCreationResponseDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.DOSI_SalesLineDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.DOSI_ResponseDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.DOSI_SalesOrderDC))]
    public partial class XppObjectBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DOSI_POCreationResponseDC", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class DOSI_POCreationResponseDC : ServiceReference1.XppObjectBase
    {
        
        private bool POCreatedField;
        
        private ServiceReference1.DOSI_SalesLineDC[] POLinesField;
        
        private System.Collections.Generic.Dictionary<int, string> headerCommentsField;
        
        private string salesIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool POCreated
        {
            get
            {
                return this.POCreatedField;
            }
            set
            {
                this.POCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DOSI_SalesLineDC[] POLines
        {
            get
            {
                return this.POLinesField;
            }
            set
            {
                this.POLinesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, string> headerComments
        {
            get
            {
                return this.headerCommentsField;
            }
            set
            {
                this.headerCommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salesId
        {
            get
            {
                return this.salesIdField;
            }
            set
            {
                this.salesIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DOSI_SalesLineDC", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class DOSI_SalesLineDC : ServiceReference1.XppObjectBase
    {
        
        private string batchIdField;
        
        private double discountField;
        
        private string itemIdField;
        
        private System.Collections.Generic.Dictionary<int, string> lineCommentsField;
        
        private int lineNumField;
        
        private double linePercentField;
        
        private double multiLnPercentField;
        
        private decimal qtyField;
        
        private string salesOrderIdField;
        
        private double salesPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string batchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itemId
        {
            get
            {
                return this.itemIdField;
            }
            set
            {
                this.itemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, string> lineComments
        {
            get
            {
                return this.lineCommentsField;
            }
            set
            {
                this.lineCommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lineNum
        {
            get
            {
                return this.lineNumField;
            }
            set
            {
                this.lineNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double linePercent
        {
            get
            {
                return this.linePercentField;
            }
            set
            {
                this.linePercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double multiLnPercent
        {
            get
            {
                return this.multiLnPercentField;
            }
            set
            {
                this.multiLnPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salesOrderId
        {
            get
            {
                return this.salesOrderIdField;
            }
            set
            {
                this.salesOrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double salesPrice
        {
            get
            {
                return this.salesPriceField;
            }
            set
            {
                this.salesPriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DOSI_ResponseDC", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class DOSI_ResponseDC : ServiceReference1.XppObjectBase
    {
        
        private System.Collections.Generic.Dictionary<int, string> commentsField;
        
        private bool responseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, string> comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DOSI_SalesOrderDC", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class DOSI_SalesOrderDC : ServiceReference1.XppObjectBase
    {
        
        private string CustomerRefField;
        
        private ServiceReference1.DOSI_SalesLineDC[] SalesLineField;
        
        private int codeCmdGHPCField;
        
        private string createdByField;
        
        private string customerIdField;
        
        private string destinationIdField;
        
        private string externalOrderIdField;
        
        private int orderTypeField;
        
        private string zoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerRef
        {
            get
            {
                return this.CustomerRefField;
            }
            set
            {
                this.CustomerRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DOSI_SalesLineDC[] SalesLine
        {
            get
            {
                return this.SalesLineField;
            }
            set
            {
                this.SalesLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codeCmdGHPC
        {
            get
            {
                return this.codeCmdGHPCField;
            }
            set
            {
                this.codeCmdGHPCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string createdBy
        {
            get
            {
                return this.createdByField;
            }
            set
            {
                this.createdByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string destinationId
        {
            get
            {
                return this.destinationIdField;
            }
            set
            {
                this.destinationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string externalOrderId
        {
            get
            {
                return this.externalOrderIdField;
            }
            set
            {
                this.externalOrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderType
        {
            get
            {
                return this.orderTypeField;
            }
            set
            {
                this.orderTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zone
        {
            get
            {
                return this.zoneField;
            }
            set
            {
                this.zoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private ServiceReference1.FaultMessageList[] FaultMessageListArrayField;
        
        private ServiceReference1.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private ServiceReference1.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private ServiceReference1.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DOSI_SalesOrderService", ConfigurationName="ServiceReference1.DOSI_SalesOrderService")]
    public interface DOSI_SalesOrderService
    {
        
        // CODEGEN: Generating message contract since the wrapper name (DOSI_SalesOrderServiceCreateSalesOrderRequest) of message DOSI_SalesOrderServiceCreateSalesOrderRequest does not match the default value (createSalesOrder)
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/createSalesOrder", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/createSalesOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.AifFault), Action="DOSI_SalesOrderService/DOSI_SalesOrderService/createSalesOrderAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderResponse createSalesOrder(ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/createSalesOrder", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/createSalesOrderResponse")]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderResponse> createSalesOrderAsync(ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DOSI_SalesOrderServiceCreateSalesLineRequest) of message DOSI_SalesOrderServiceCreateSalesLineRequest does not match the default value (createSalesLine)
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/createSalesLine", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/createSalesLineResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.AifFault), Action="DOSI_SalesOrderService/DOSI_SalesOrderService/createSalesLineAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineResponse createSalesLine(ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/createSalesLine", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/createSalesLineResponse")]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineResponse> createSalesLineAsync(ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DOSI_SalesOrderServiceCreateSOfromPORequest) of message DOSI_SalesOrderServiceCreateSOfromPORequest does not match the default value (createSOfromPO)
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/createSOfromPO", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/createSOfromPOResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.AifFault), Action="DOSI_SalesOrderService/DOSI_SalesOrderService/createSOfromPOAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPOResponse createSOfromPO(ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/createSOfromPO", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/createSOfromPOResponse")]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPOResponse> createSOfromPOAsync(ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPORequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DOSI_SalesOrderServiceCheckOrderRequest) of message DOSI_SalesOrderServiceCheckOrderRequest does not match the default value (checkOrder)
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/checkOrder", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/checkOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.AifFault), Action="DOSI_SalesOrderService/DOSI_SalesOrderService/checkOrderAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        ServiceReference1.DOSI_SalesOrderServiceCheckOrderResponse checkOrder(ServiceReference1.DOSI_SalesOrderServiceCheckOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/checkOrder", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/checkOrderResponse")]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCheckOrderResponse> checkOrderAsync(ServiceReference1.DOSI_SalesOrderServiceCheckOrderRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DOSI_SalesOrderServiceInvoiceRequest) of message DOSI_SalesOrderServiceInvoiceRequest does not match the default value (invoice)
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/invoice", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/invoiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.AifFault), Action="DOSI_SalesOrderService/DOSI_SalesOrderService/invoiceAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        ServiceReference1.DOSI_SalesOrderServiceInvoiceResponse invoice(ServiceReference1.DOSI_SalesOrderServiceInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/invoice", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/invoiceResponse")]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceInvoiceResponse> invoiceAsync(ServiceReference1.DOSI_SalesOrderServiceInvoiceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DOSI_SalesOrderServiceUpdatePackageRequest) of message DOSI_SalesOrderServiceUpdatePackageRequest does not match the default value (updatePackage)
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/updatePackage", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/updatePackageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.AifFault), Action="DOSI_SalesOrderService/DOSI_SalesOrderService/updatePackageAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        ServiceReference1.DOSI_SalesOrderServiceUpdatePackageResponse updatePackage(ServiceReference1.DOSI_SalesOrderServiceUpdatePackageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/updatePackage", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/updatePackageResponse")]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceUpdatePackageResponse> updatePackageAsync(ServiceReference1.DOSI_SalesOrderServiceUpdatePackageRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DOSI_SalesOrderServiceCancelSalesOrderRequest) of message DOSI_SalesOrderServiceCancelSalesOrderRequest does not match the default value (cancelSalesOrder)
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/cancelSalesOrder", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/cancelSalesOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.AifFault), Action="DOSI_SalesOrderService/DOSI_SalesOrderService/cancelSalesOrderAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderResponse cancelSalesOrder(ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DOSI_SalesOrderService/DOSI_SalesOrderService/cancelSalesOrder", ReplyAction="DOSI_SalesOrderService/DOSI_SalesOrderService/cancelSalesOrderResponse")]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderResponse> cancelSalesOrderAsync(ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceCreateSalesOrderRequest", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceCreateSalesOrderRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public ServiceReference1.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public ServiceReference1.DOSI_SalesOrderDC salesOrderObj;
        
        public DOSI_SalesOrderServiceCreateSalesOrderRequest()
        {
        }
        
        public DOSI_SalesOrderServiceCreateSalesOrderRequest(ServiceReference1.CallContext CallContext, ServiceReference1.DOSI_SalesOrderDC salesOrderObj)
        {
            this.CallContext = CallContext;
            this.salesOrderObj = salesOrderObj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceCreateSalesOrderResponse", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceCreateSalesOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public string response;
        
        public DOSI_SalesOrderServiceCreateSalesOrderResponse()
        {
        }
        
        public DOSI_SalesOrderServiceCreateSalesOrderResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceCreateSalesLineRequest", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceCreateSalesLineRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public ServiceReference1.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public ServiceReference1.DOSI_SalesLineDC salesLineObj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=1)]
        public string salesId;
        
        public DOSI_SalesOrderServiceCreateSalesLineRequest()
        {
        }
        
        public DOSI_SalesOrderServiceCreateSalesLineRequest(ServiceReference1.CallContext CallContext, ServiceReference1.DOSI_SalesLineDC salesLineObj, string salesId)
        {
            this.CallContext = CallContext;
            this.salesLineObj = salesLineObj;
            this.salesId = salesId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceCreateSalesLineResponse", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceCreateSalesLineResponse
    {
        
        public DOSI_SalesOrderServiceCreateSalesLineResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceCreateSOfromPORequest", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceCreateSOfromPORequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public ServiceReference1.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public ServiceReference1.DOSI_SalesOrderDC salesOrderObj;
        
        public DOSI_SalesOrderServiceCreateSOfromPORequest()
        {
        }
        
        public DOSI_SalesOrderServiceCreateSOfromPORequest(ServiceReference1.CallContext CallContext, ServiceReference1.DOSI_SalesOrderDC salesOrderObj)
        {
            this.CallContext = CallContext;
            this.salesOrderObj = salesOrderObj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceCreateSOfromPOResponse", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceCreateSOfromPOResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public ServiceReference1.DOSI_POCreationResponseDC response;
        
        public DOSI_SalesOrderServiceCreateSOfromPOResponse()
        {
        }
        
        public DOSI_SalesOrderServiceCreateSOfromPOResponse(ServiceReference1.DOSI_POCreationResponseDC response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceCheckOrderRequest", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceCheckOrderRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public ServiceReference1.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public string _customerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=1)]
        public string _salesperson;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=2)]
        public double _custBalance;
        
        public DOSI_SalesOrderServiceCheckOrderRequest()
        {
        }
        
        public DOSI_SalesOrderServiceCheckOrderRequest(ServiceReference1.CallContext CallContext, string _customerId, string _salesperson, double _custBalance)
        {
            this.CallContext = CallContext;
            this._customerId = _customerId;
            this._salesperson = _salesperson;
            this._custBalance = _custBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceCheckOrderResponse", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceCheckOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public ServiceReference1.DOSI_ResponseDC response;
        
        public DOSI_SalesOrderServiceCheckOrderResponse()
        {
        }
        
        public DOSI_SalesOrderServiceCheckOrderResponse(ServiceReference1.DOSI_ResponseDC response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceInvoiceRequest", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceInvoiceRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public ServiceReference1.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public string _salesId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=1)]
        public int _totalPackageAmbiant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=2)]
        public int _totalPackageThermolabile;
        
        public DOSI_SalesOrderServiceInvoiceRequest()
        {
        }
        
        public DOSI_SalesOrderServiceInvoiceRequest(ServiceReference1.CallContext CallContext, string _salesId, int _totalPackageAmbiant, int _totalPackageThermolabile)
        {
            this.CallContext = CallContext;
            this._salesId = _salesId;
            this._totalPackageAmbiant = _totalPackageAmbiant;
            this._totalPackageThermolabile = _totalPackageThermolabile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceInvoiceResponse", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceInvoiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public ServiceReference1.DOSI_ResponseDC response;
        
        public DOSI_SalesOrderServiceInvoiceResponse()
        {
        }
        
        public DOSI_SalesOrderServiceInvoiceResponse(ServiceReference1.DOSI_ResponseDC response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceUpdatePackageRequest", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceUpdatePackageRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public ServiceReference1.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public string _salesId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=1)]
        public int _totalPackageAmbiant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=2)]
        public int _totalPackageThermolabile;
        
        public DOSI_SalesOrderServiceUpdatePackageRequest()
        {
        }
        
        public DOSI_SalesOrderServiceUpdatePackageRequest(ServiceReference1.CallContext CallContext, string _salesId, int _totalPackageAmbiant, int _totalPackageThermolabile)
        {
            this.CallContext = CallContext;
            this._salesId = _salesId;
            this._totalPackageAmbiant = _totalPackageAmbiant;
            this._totalPackageThermolabile = _totalPackageThermolabile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceUpdatePackageResponse", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceUpdatePackageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public bool response;
        
        public DOSI_SalesOrderServiceUpdatePackageResponse()
        {
        }
        
        public DOSI_SalesOrderServiceUpdatePackageResponse(bool response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceCancelSalesOrderRequest", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceCancelSalesOrderRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public ServiceReference1.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public string _salesId;
        
        public DOSI_SalesOrderServiceCancelSalesOrderRequest()
        {
        }
        
        public DOSI_SalesOrderServiceCancelSalesOrderRequest(ServiceReference1.CallContext CallContext, string _salesId)
        {
            this.CallContext = CallContext;
            this._salesId = _salesId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DOSI_SalesOrderServiceCancelSalesOrderResponse", WrapperNamespace="DOSI_SalesOrderService", IsWrapped=true)]
    public partial class DOSI_SalesOrderServiceCancelSalesOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="DOSI_SalesOrderService", Order=0)]
        public ServiceReference1.DOSI_ResponseDC response;
        
        public DOSI_SalesOrderServiceCancelSalesOrderResponse()
        {
        }
        
        public DOSI_SalesOrderServiceCancelSalesOrderResponse(ServiceReference1.DOSI_ResponseDC response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface DOSI_SalesOrderServiceChannel : ServiceReference1.DOSI_SalesOrderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class DOSI_SalesOrderServiceClient : System.ServiceModel.ClientBase<ServiceReference1.DOSI_SalesOrderService>, ServiceReference1.DOSI_SalesOrderService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DOSI_SalesOrderServiceClient() : 
                base(DOSI_SalesOrderServiceClient.GetDefaultBinding(), DOSI_SalesOrderServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_DOSI_SalesOrderService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DOSI_SalesOrderServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(DOSI_SalesOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), DOSI_SalesOrderServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DOSI_SalesOrderServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DOSI_SalesOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DOSI_SalesOrderServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DOSI_SalesOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DOSI_SalesOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderResponse ServiceReference1.DOSI_SalesOrderService.createSalesOrder(ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderRequest request)
        {
            return base.Channel.createSalesOrder(request);
        }
        
        public string createSalesOrder(ServiceReference1.CallContext CallContext, ServiceReference1.DOSI_SalesOrderDC salesOrderObj)
        {
            ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderRequest();
            inValue.CallContext = CallContext;
            inValue.salesOrderObj = salesOrderObj;
            ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderResponse retVal = ((ServiceReference1.DOSI_SalesOrderService)(this)).createSalesOrder(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderResponse> ServiceReference1.DOSI_SalesOrderService.createSalesOrderAsync(ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderRequest request)
        {
            return base.Channel.createSalesOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderResponse> createSalesOrderAsync(ServiceReference1.CallContext CallContext, ServiceReference1.DOSI_SalesOrderDC salesOrderObj)
        {
            ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceCreateSalesOrderRequest();
            inValue.CallContext = CallContext;
            inValue.salesOrderObj = salesOrderObj;
            return ((ServiceReference1.DOSI_SalesOrderService)(this)).createSalesOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineResponse ServiceReference1.DOSI_SalesOrderService.createSalesLine(ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineRequest request)
        {
            return base.Channel.createSalesLine(request);
        }
        
        public void createSalesLine(ServiceReference1.CallContext CallContext, ServiceReference1.DOSI_SalesLineDC salesLineObj, string salesId)
        {
            ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineRequest();
            inValue.CallContext = CallContext;
            inValue.salesLineObj = salesLineObj;
            inValue.salesId = salesId;
            ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineResponse retVal = ((ServiceReference1.DOSI_SalesOrderService)(this)).createSalesLine(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineResponse> ServiceReference1.DOSI_SalesOrderService.createSalesLineAsync(ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineRequest request)
        {
            return base.Channel.createSalesLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineResponse> createSalesLineAsync(ServiceReference1.CallContext CallContext, ServiceReference1.DOSI_SalesLineDC salesLineObj, string salesId)
        {
            ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceCreateSalesLineRequest();
            inValue.CallContext = CallContext;
            inValue.salesLineObj = salesLineObj;
            inValue.salesId = salesId;
            return ((ServiceReference1.DOSI_SalesOrderService)(this)).createSalesLineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPOResponse ServiceReference1.DOSI_SalesOrderService.createSOfromPO(ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPORequest request)
        {
            return base.Channel.createSOfromPO(request);
        }
        
        public ServiceReference1.DOSI_POCreationResponseDC createSOfromPO(ServiceReference1.CallContext CallContext, ServiceReference1.DOSI_SalesOrderDC salesOrderObj)
        {
            ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPORequest inValue = new ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPORequest();
            inValue.CallContext = CallContext;
            inValue.salesOrderObj = salesOrderObj;
            ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPOResponse retVal = ((ServiceReference1.DOSI_SalesOrderService)(this)).createSOfromPO(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPOResponse> ServiceReference1.DOSI_SalesOrderService.createSOfromPOAsync(ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPORequest request)
        {
            return base.Channel.createSOfromPOAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPOResponse> createSOfromPOAsync(ServiceReference1.CallContext CallContext, ServiceReference1.DOSI_SalesOrderDC salesOrderObj)
        {
            ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPORequest inValue = new ServiceReference1.DOSI_SalesOrderServiceCreateSOfromPORequest();
            inValue.CallContext = CallContext;
            inValue.salesOrderObj = salesOrderObj;
            return ((ServiceReference1.DOSI_SalesOrderService)(this)).createSOfromPOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.DOSI_SalesOrderServiceCheckOrderResponse ServiceReference1.DOSI_SalesOrderService.checkOrder(ServiceReference1.DOSI_SalesOrderServiceCheckOrderRequest request)
        {
            return base.Channel.checkOrder(request);
        }
        
        public ServiceReference1.DOSI_ResponseDC checkOrder(ServiceReference1.CallContext CallContext, string _customerId, string _salesperson, double _custBalance)
        {
            ServiceReference1.DOSI_SalesOrderServiceCheckOrderRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceCheckOrderRequest();
            inValue.CallContext = CallContext;
            inValue._customerId = _customerId;
            inValue._salesperson = _salesperson;
            inValue._custBalance = _custBalance;
            ServiceReference1.DOSI_SalesOrderServiceCheckOrderResponse retVal = ((ServiceReference1.DOSI_SalesOrderService)(this)).checkOrder(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCheckOrderResponse> ServiceReference1.DOSI_SalesOrderService.checkOrderAsync(ServiceReference1.DOSI_SalesOrderServiceCheckOrderRequest request)
        {
            return base.Channel.checkOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCheckOrderResponse> checkOrderAsync(ServiceReference1.CallContext CallContext, string _customerId, string _salesperson, double _custBalance)
        {
            ServiceReference1.DOSI_SalesOrderServiceCheckOrderRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceCheckOrderRequest();
            inValue.CallContext = CallContext;
            inValue._customerId = _customerId;
            inValue._salesperson = _salesperson;
            inValue._custBalance = _custBalance;
            return ((ServiceReference1.DOSI_SalesOrderService)(this)).checkOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.DOSI_SalesOrderServiceInvoiceResponse ServiceReference1.DOSI_SalesOrderService.invoice(ServiceReference1.DOSI_SalesOrderServiceInvoiceRequest request)
        {
            return base.Channel.invoice(request);
        }
        
        public ServiceReference1.DOSI_ResponseDC invoice(ServiceReference1.CallContext CallContext, string _salesId, int _totalPackageAmbiant, int _totalPackageThermolabile)
        {
            ServiceReference1.DOSI_SalesOrderServiceInvoiceRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceInvoiceRequest();
            inValue.CallContext = CallContext;
            inValue._salesId = _salesId;
            inValue._totalPackageAmbiant = _totalPackageAmbiant;
            inValue._totalPackageThermolabile = _totalPackageThermolabile;
            ServiceReference1.DOSI_SalesOrderServiceInvoiceResponse retVal = ((ServiceReference1.DOSI_SalesOrderService)(this)).invoice(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceInvoiceResponse> ServiceReference1.DOSI_SalesOrderService.invoiceAsync(ServiceReference1.DOSI_SalesOrderServiceInvoiceRequest request)
        {
            return base.Channel.invoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceInvoiceResponse> invoiceAsync(ServiceReference1.CallContext CallContext, string _salesId, int _totalPackageAmbiant, int _totalPackageThermolabile)
        {
            ServiceReference1.DOSI_SalesOrderServiceInvoiceRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceInvoiceRequest();
            inValue.CallContext = CallContext;
            inValue._salesId = _salesId;
            inValue._totalPackageAmbiant = _totalPackageAmbiant;
            inValue._totalPackageThermolabile = _totalPackageThermolabile;
            return ((ServiceReference1.DOSI_SalesOrderService)(this)).invoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.DOSI_SalesOrderServiceUpdatePackageResponse ServiceReference1.DOSI_SalesOrderService.updatePackage(ServiceReference1.DOSI_SalesOrderServiceUpdatePackageRequest request)
        {
            return base.Channel.updatePackage(request);
        }
        
        public bool updatePackage(ServiceReference1.CallContext CallContext, string _salesId, int _totalPackageAmbiant, int _totalPackageThermolabile)
        {
            ServiceReference1.DOSI_SalesOrderServiceUpdatePackageRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceUpdatePackageRequest();
            inValue.CallContext = CallContext;
            inValue._salesId = _salesId;
            inValue._totalPackageAmbiant = _totalPackageAmbiant;
            inValue._totalPackageThermolabile = _totalPackageThermolabile;
            ServiceReference1.DOSI_SalesOrderServiceUpdatePackageResponse retVal = ((ServiceReference1.DOSI_SalesOrderService)(this)).updatePackage(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceUpdatePackageResponse> ServiceReference1.DOSI_SalesOrderService.updatePackageAsync(ServiceReference1.DOSI_SalesOrderServiceUpdatePackageRequest request)
        {
            return base.Channel.updatePackageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceUpdatePackageResponse> updatePackageAsync(ServiceReference1.CallContext CallContext, string _salesId, int _totalPackageAmbiant, int _totalPackageThermolabile)
        {
            ServiceReference1.DOSI_SalesOrderServiceUpdatePackageRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceUpdatePackageRequest();
            inValue.CallContext = CallContext;
            inValue._salesId = _salesId;
            inValue._totalPackageAmbiant = _totalPackageAmbiant;
            inValue._totalPackageThermolabile = _totalPackageThermolabile;
            return ((ServiceReference1.DOSI_SalesOrderService)(this)).updatePackageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderResponse ServiceReference1.DOSI_SalesOrderService.cancelSalesOrder(ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderRequest request)
        {
            return base.Channel.cancelSalesOrder(request);
        }
        
        public ServiceReference1.DOSI_ResponseDC cancelSalesOrder(ServiceReference1.CallContext CallContext, string _salesId)
        {
            ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderRequest();
            inValue.CallContext = CallContext;
            inValue._salesId = _salesId;
            ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderResponse retVal = ((ServiceReference1.DOSI_SalesOrderService)(this)).cancelSalesOrder(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderResponse> ServiceReference1.DOSI_SalesOrderService.cancelSalesOrderAsync(ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderRequest request)
        {
            return base.Channel.cancelSalesOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderResponse> cancelSalesOrderAsync(ServiceReference1.CallContext CallContext, string _salesId)
        {
            ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderRequest inValue = new ServiceReference1.DOSI_SalesOrderServiceCancelSalesOrderRequest();
            inValue.CallContext = CallContext;
            inValue._salesId = _salesId;
            return ((ServiceReference1.DOSI_SalesOrderService)(this)).cancelSalesOrderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_DOSI_SalesOrderService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_DOSI_SalesOrderService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://adaxaos-test:8201/DynamicsAx/Services/DOSI_SalesOrderServiceGroup");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DOSI_SalesOrderServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_DOSI_SalesOrderService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DOSI_SalesOrderServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_DOSI_SalesOrderService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_DOSI_SalesOrderService,
        }
    }
}
